#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
import tkinter as tk

import os
#definimos una funcion que indique que al presionar el boton
#se imprima el texto ingresado en la caja

"""
durante la ejecucion del programa se sobreescribe el archivi
al salir del programa se guarda el archivo
al abrir el programa se crea nuevo archivo
"""

def boton_presionado():
	tiket_full=("Producto: "+str(caja_producto.get())+" Precio: "+str(caja_monto.get()))
	print(tiket_full)
	file = open("tiket.txt", "a+")
	file.write(tiket_full+"\n")
	file.close()
	

ventana = tk.Tk()
ventana.config(width=400, height=300)
ventana.title("Primera aplicacion de escritorio")

boton=tk.Button(text="Guardar tiket", command=boton_presionado)
boton.place(x=20, y=50, width=120, height=30)

etiqueta_producto=tk.Label(text="Ingresar producto:")
etiqueta_producto.place(x=30, y=100)
caja_producto=tk.Entry()
caja_producto.place(x=29, y=120, width=200, height=25)

etiqueta_monto=tk.Label(text="Ingresar monto:")
etiqueta_monto.place(x=30, y=160)
caja_monto=tk.Entry()
caja_monto.place(x=29, y=190, width=200, height=25)




ventana.mainloop()

